### ISSUE TITLE
Project Setup Review

### ISSUE THREAD

**Issue by dodoburner** [dodoburner/cat-gallery#21]
There are 2 people in this project; Dorian Urem and Aleksandra Ujvari. Can you kindly review if everything is setup correctly. Here is the [link](https://github.com/dodoburner/cat-gallery/projects/1) to the kanban board.

**Comment by muneebulrehman** [comment]
Kindly mention the name of your partners along with yours in the description of the issue. Also, consider adding a link to the Kanban board in the issue description.

**Comment by elmar8287** [comment]
Hi, @dodoburner and @digia3d.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- Nice, you have fixed the suggestions from the previous previewer 💯 

### Optional suggestions

- [ ] Please, consider that if all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
<img width="351" alt="Screen Shot 2022-07-25 at 14 22 18" src="https://user-images.githubusercontent.com/49064106/180755161-fd84e549-abe7-4074-bfef-3f571e5644c5.png">

- [ ] Please, consider who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
- [ ] All cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that).

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
